#include "web_dashboard.h"
#include "esp_log.h"
#include "esp_timer.h"
#include "esp_system.h"
#include "esp_app_format.h"
#include "temperature.h"
#include <inttypes.h>
#include <string.h>

esp_err_t status_handler(httpd_req_t *req)
{
    char resp_str[768];  // Increased buffer size for temperature data
    snprintf(resp_str, sizeof(resp_str),
        "{"
        "\"firmware_version\":\"%s\","
        "\"heap_free\":%" PRIu32 ","
        "\"uptime\":%lld,"
        "\"flow_in\":%.3f,"
        "\"flow_out\":%.3f,"
        "\"servo_angle\":%.1f,"
        "\"mode\":\"%s\","
        "\"setpoint\":%.3f,"
        "\"pid_enabled\":%s,"
        "\"temp1_c\":%.2f,"
        "\"temp1_f\":%.2f,"
        "\"temp1_valid\":%s,"
        "\"temp2_c\":%.2f,"
        "\"temp2_f\":%.2f,"
        "\"temp2_valid\":%s"
        "}",
        "1.0.0",
        esp_get_free_heap_size(),
        esp_timer_get_time() / 1000000LL,
        lpm_in,
        lpm_out,
        servoAngleDeg,
        MODE_EQUALIZE ? "EQUALIZE" : "SETPOINT",
        SETPOINT_LPM,
        pidEnabled ? "true" : "false",
        temp_sensor_1.temperature_c,
        temp_sensor_1.temperature_f,
        temp_sensor_1.valid ? "true" : "false",
        temp_sensor_2.temperature_c,
        temp_sensor_2.temperature_f,
        temp_sensor_2.valid ? "true" : "false"
    );
    
    httpd_resp_set_type(req, "application/json");
    httpd_resp_send(req, resp_str, strlen(resp_str));
    return ESP_OK;
}

esp_err_t dashboard_handler(httpd_req_t *req)
{
    const char* html_page = 
    "<!DOCTYPE html>"
    "<html><head>"
    "<title>T500 Flow Meter Dashboard</title>"
    "<meta name='viewport' content='width=device-width, initial-scale=1'>"
    "<style>"
    "body { font-family: Arial, sans-serif; margin: 20px; background: #f5f5f5; }"
    ".container { max-width: 1200px; margin: 0 auto; }"
    ".header { background: #2c3e50; color: white; padding: 20px; border-radius: 8px; margin-bottom: 20px; }"
    ".card { background: white; border-radius: 8px; padding: 20px; margin-bottom: 20px; box-shadow: 0 2px 4px rgba(0,0,0,0.1); }"
    ".status-grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(200px, 1fr)); gap: 15px; }"
    ".status-item { background: #ecf0f1; padding: 15px; border-radius: 6px; text-align: center; }"
    ".status-value { font-size: 24px; font-weight: bold; color: #2c3e50; }"
    ".status-label { font-size: 14px; color: #7f8c8d; }"
    ".flow-meters { display: grid; grid-template-columns: 1fr 1fr; gap: 20px; }"
    ".flow-meter { text-align: center; }"
    ".flow-value { font-size: 36px; font-weight: bold; }"
    ".flow-in { color: #3498db; }"
    ".flow-out { color: #e74c3c; }"
    ".controls { display: grid; grid-template-columns: repeat(auto-fit, minmax(250px, 1fr)); gap: 15px; }"
    ".control-group { background: #ecf0f1; padding: 15px; border-radius: 6px; }"
    ".button { background: #3498db; color: white; border: none; padding: 10px 20px; border-radius: 4px; cursor: pointer; margin: 5px; }"
    ".button:hover { background: #2980b9; }"
    ".button.danger { background: #e74c3c; }"
    ".button.danger:hover { background: #c0392b; }"
    ".button.success { background: #27ae60; }"
    ".button.success:hover { background: #229954; }"
    ".input { padding: 8px; border: 1px solid #bdc3c7; border-radius: 4px; width: 100px; }"
    ".servo-indicator { width: 200px; height: 20px; background: #ecf0f1; border-radius: 10px; position: relative; margin: 0 auto; }"
    ".servo-position { height: 100%; background: #3498db; border-radius: 10px; transition: width 0.3s ease; }"
    ".online { color: #27ae60; }"
    ".offline { color: #e74c3c; }"
    "</style>"
    "<script>"
    "let updateInterval;"
    "function updateData() {"
    "  fetch('/status')"
    "    .then(response => response.json())"
    "    .then(data => {"
    "      document.getElementById('firmware').textContent = data.firmware_version;"
    "      document.getElementById('uptime').textContent = formatUptime(data.uptime);"
    "      document.getElementById('heap').textContent = formatBytes(data.heap_free);"
    "      document.getElementById('flow-in').textContent = data.flow_in.toFixed(3);"
    "      document.getElementById('flow-out').textContent = data.flow_out.toFixed(3);"
    "      document.getElementById('servo-angle').textContent = data.servo_angle.toFixed(1) + '°';"
    "      document.getElementById('mode').textContent = data.mode;"
    "      document.getElementById('setpoint').textContent = data.setpoint.toFixed(2);"
    "      document.getElementById('pid-status').textContent = data.pid_enabled ? 'ENABLED' : 'DISABLED';"
    "      document.getElementById('pid-status').className = data.pid_enabled ? 'online' : 'offline';"
    "      document.getElementById('ota-status').textContent = data.ota_in_progress ? 'IN PROGRESS' : 'READY';"
    "      document.getElementById('ota-status').className = data.ota_in_progress ? 'offline' : 'online';"
    "      document.getElementById('temp1-c').textContent = data.temp1_valid ? data.temp1_c.toFixed(2) + '°C' : '--°C';"
    "      document.getElementById('temp1-f').textContent = data.temp1_valid ? data.temp1_f.toFixed(2) + '°F' : '--°F';"
    "      document.getElementById('temp1-status').textContent = data.temp1_valid ? 'VALID' : 'INVALID';"
    "      document.getElementById('temp1-status').className = data.temp1_valid ? 'online' : 'offline';"
    "      document.getElementById('temp2-c').textContent = data.temp2_valid ? data.temp2_c.toFixed(2) + '°C' : '--°C';"
    "      document.getElementById('temp2-f').textContent = data.temp2_valid ? data.temp2_f.toFixed(2) + '°F' : '--°F';"
    "      document.getElementById('temp2-status').textContent = data.temp2_valid ? 'VALID' : 'INVALID';"
    "      document.getElementById('temp2-status').className = data.temp2_valid ? 'online' : 'offline';"
    "      updateServoIndicator(data.servo_angle);"
    "      document.getElementById('status').textContent = 'Online';"
    "      document.getElementById('status').className = 'online';"
    "    })"
    "    .catch(error => {"
    "      document.getElementById('status').textContent = 'Offline';"
    "      document.getElementById('status').className = 'offline';"
    "    });"
    "}"
    "function formatUptime(seconds) {"
    "  const days = Math.floor(seconds / 86400);"
    "  const hours = Math.floor((seconds % 86400) / 3600);"
    "  const mins = Math.floor((seconds % 3600) / 60);"
    "  return days + 'd ' + hours + 'h ' + mins + 'm';"
    "}"
    "function formatBytes(bytes) {"
    "  if (bytes === 0) return '0 B';"
    "  const k = 1024;"
    "  const sizes = ['B', 'KB', 'MB'];"
    "  const i = Math.floor(Math.log(bytes) / Math.log(k));"
    "  return parseFloat((bytes / Math.pow(k, i)).toFixed(2)) + ' ' + sizes[i];"
    "}"
    "function updateServoIndicator(angle) {"
    "  const percentage = ((angle - 10) / (170 - 10)) * 100;"
    "  document.getElementById('servo-bar').style.width = percentage + '%';"
    "}"
    "function triggerOTA() {"
    "  if (confirm('Are you sure you want to start OTA update?')) {"
    "    fetch('/ota', { method: 'POST' })"
    "      .then(response => response.text())"
    "      .then(data => alert(data));"
    "  }"
    "}"
    "function setMode(mode) {"
    "  // This would need additional endpoints to implement"
    "  alert('Mode change: ' + mode + ' (Serial command: m' + mode + ')');"
    "}"
    "function startUpdates() {"
    "  updateData();"
    "  updateInterval = setInterval(updateData, 2000);"
    "}"
    "function stopUpdates() {"
    "  clearInterval(updateInterval);"
    "}"
    "window.onload = startUpdates;"
    "window.onbeforeunload = stopUpdates;"
    "</script>"
    "</head><body>"
    "<div class='container'>"
    "<div class='header'>"
    "<h1>🌡️ T500 Distillation Flow Meter</h1>"
    "<p>Real-time monitoring and control dashboard</p>"
    "</div>"
    
    "<div class='card'>"
    "<h2>System Status</h2>"
    "<div class='status-grid'>"
    "<div class='status-item'>"
    "<div class='status-label'>Connection</div>"
    "<div class='status-value' id='status'>Connecting...</div>"
    "</div>"
    "<div class='status-item'>"
    "<div class='status-label'>Firmware</div>"
    "<div class='status-value' id='firmware'>Loading...</div>"
    "</div>"
    "<div class='status-item'>"
    "<div class='status-label'>Uptime</div>"
    "<div class='status-value' id='uptime'>Loading...</div>"
    "</div>"
    "<div class='status-item'>"
    "<div class='status-label'>Free Memory</div>"
    "<div class='status-value' id='heap'>Loading...</div>"
    "</div>"
    "<div class='status-item'>"
    "<div class='status-label'>PID Control</div>"
    "<div class='status-value' id='pid-status'>Loading...</div>"
    "</div>"
    "<div class='status-item'>"
    "<div class='status-label'>OTA Status</div>"
    "<div class='status-value' id='ota-status'>Loading...</div>"
    "</div>"
    "</div>"
    "</div>"
    
    "<div class='card'>"
    "<h2>Flow Rates</h2>"
    "<div class='flow-meters'>"
    "<div class='flow-meter'>"
    "<h3>Input Flow</h3>"
    "<div class='flow-value flow-in' id='flow-in'>0.000</div>"
    "<div>L/min</div>"
    "</div>"
    "<div class='flow-meter'>"
    "<h3>Output Flow</h3>"
    "<div class='flow-value flow-out' id='flow-out'>0.000</div>"
    "<div>L/min</div>"
    "</div>"
    "</div>"
    "</div>"
    
    "<div class='card'>"
    "<h2>Temperature Monitoring</h2>"
    "<div class='flow-meters'>"
    "<div class='flow-meter'>"
    "<h3>🌡️ Temperature Sensor 1</h3>"
    "<div class='flow-value' style='color: #e67e22;' id='temp1-c'>--°C</div>"
    "<div class='flow-value' style='color: #e67e22; font-size: 24px;' id='temp1-f'>--°F</div>"
    "<div class='status-value' id='temp1-status'>Loading...</div>"
    "</div>"
    "<div class='flow-meter'>"
    "<h3>🌡️ Temperature Sensor 2</h3>"
    "<div class='flow-value' style='color: #e67e22;' id='temp2-c'>--°C</div>"
    "<div class='flow-value' style='color: #e67e22; font-size: 24px;' id='temp2-f'>--°F</div>"
    "<div class='status-value' id='temp2-status'>Loading...</div>"
    "</div>"
    "</div>"
    "</div>"
    
    "<div class='card'>"
    "<h2>Servo Control</h2>"
    "<div style='text-align: center;'>"
    "<h3>Current Position: <span id='servo-angle'>90.0°</span></h3>"
    "<div class='servo-indicator'>"
    "<div class='servo-position' id='servo-bar'></div>"
    "</div>"
    "<p style='color: #7f8c8d; margin-top: 10px;'>10° (min) ← → 170° (max)</p>"
    "</div>"
    "</div>"
    
    "<div class='card'>"
    "<h2>Control Panel</h2>"
    "<div class='controls'>"
    "<div class='control-group'>"
    "<h4>Operating Mode</h4>"
    "<p><strong>Current:</strong> <span id='mode'>Loading...</span></p>"
    "<button class='button' onclick='setMode(0)'>Setpoint Mode</button>"
    "<button class='button' onclick='setMode(1)'>Equalize Mode</button>"
    "</div>"
    "<div class='control-group'>"
    "<h4>Setpoint</h4>"
    "<p><strong>Current:</strong> <span id='setpoint'>0.00</span> L/min</p>"
    "<input type='number' class='input' id='setpoint-input' step='0.1' placeholder='3.0'>"
    "<button class='button success'>Set Setpoint</button>"
    "</div>"
    "<div class='control-group'>"
    "<h4>System Control</h4>"
    "<button class='button danger' onclick='triggerOTA()'>🔄 OTA Update</button>"
    "<button class='button' onclick='location.reload()'>🔄 Refresh</button>"
    "</div>"
    "</div>"
    "</div>"
    
    "<div class='card'>"
    "<h2>Instructions</h2>"
    "<p><strong>Control via Serial:</strong> Connect via <code>idf.py monitor</code> for full control</p>"
    "<ul>"
    "<li><code>m0</code> / <code>m1</code> - Switch modes</li>"
    "<li><code>s3.5</code> - Set setpoint to 3.5 L/min</li>"
    "<li><code>p0.8 i0.05 d0.02</code> - Adjust PID parameters</li>"
    "<li><code>status</code> - Show detailed status</li>"
    "<li><code>ota</code> - Trigger OTA update</li>"
    "</ul>"
    "</div>"
    
    "</div>"
    "</body></html>";
    
    httpd_resp_set_type(req, "text/html");
    httpd_resp_send(req, html_page, strlen(html_page));
    return ESP_OK;
}
